import {
  Sparkles,
  Sun,
  CalendarDays,
  Compass,
  FileText,
  FolderOpen,
  Gamepad2,
  Library,
  ListChecks,
  MessageCircle,
  MessagesSquare,
  Network,
  PenLine,
  Presentation,
  Radio,
  Repeat,
  Settings,
  PenTool,
  Sheet,
  ShieldCheck,
  StickyNote,
  Swords,
  Target,
  TrendingUp,
  UserRound,
  Users,
  Video,
  Newspaper,
  type LucideIcon,
} from "lucide-react"
import type { View } from "./types"

/**
 * One icon per view, shared by the sidebar, the phone dock, the tab rows and the
 * command palette. A place wears the icon of its own view: Create is a pen and
 * Friends are people, so group chats get the speech bubbles.
 */
export const viewIcons: Record<View, LucideIcon> = {
  admin: ShieldCheck,
  ai: Sparkles,
  battles: Swords,
  calendar: CalendarDays,
  canvas: PenTool,
  chat: MessageCircle,
  dashboard: Sun,
  discover: Compass,
  docs: FileText,
  feed: Newspaper,
  files: FolderOpen,
  games: Gamepad2,
  graph: Network,
  live: Radio,
  notes: StickyNote,
  practice: Target,
  profile: UserRound,
  progress: TrendingUp,
  quizzes: ListChecks,
  reviews: Repeat,
  rooms: Video,
  settings: Settings,
  sheets: Sheet,
  slides: Presentation,
  social: Users,
  spaces: MessagesSquare,
  studio: PenLine,
  vault: Library,
}
