import {
  Bot,
  CalendarDays,
  Compass,
  FileText,
  FolderOpen,
  Gamepad2,
  Home,
  Library,
  ListChecks,
  MessageCircle,
  MessagesSquare,
  Network,
  NotebookPen,
  Presentation,
  Radio,
  Repeat,
  Settings,
  Shapes,
  Sheet,
  ShieldCheck,
  StickyNote,
  Swords,
  Target,
  TrendingUp,
  UserRound,
  Users,
  Video,
  Newspaper,
  type LucideIcon,
} from "lucide-react"
import type { View } from "./types"

/** One icon per view, shared by the sidebar, the mobile tabs and the command palette. */
export const viewIcons: Record<View, LucideIcon> = {
  admin: ShieldCheck,
  ai: Bot,
  battles: Swords,
  calendar: CalendarDays,
  canvas: Shapes,
  chat: MessageCircle,
  dashboard: Home,
  discover: Compass,
  docs: FileText,
  feed: Newspaper,
  files: FolderOpen,
  games: Gamepad2,
  graph: Network,
  live: Radio,
  notes: StickyNote,
  practice: Target,
  profile: UserRound,
  progress: TrendingUp,
  quizzes: ListChecks,
  reviews: Repeat,
  rooms: Video,
  settings: Settings,
  sheets: Sheet,
  slides: Presentation,
  social: MessagesSquare,
  spaces: Users,
  studio: NotebookPen,
  vault: Library,
}
